title: "Nicolin Dora"
description: "Security Analyst • Student • Maker"
url: "https://nicolin-dora.ch"
baseurl: ""
locale: "de-CH"
show_banner: true

# Autorprofil
author:
  name: "Nicolin Dora"
  avatar: "/assets/images/avatar.jpg"
  bio: "Kurzprofil folgt."
  location: "Bern/Biel, Schweiz"
  links:
    - label: "E-Mail"
      icon: "fas fa-envelope"
      url: "mailto:mail@nicolin-dora.ch"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/devobern"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/<dein-handle>/"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

collections:
  posts:
    output: true
    permalink: /blog/:title/
  pages:
    output: true
    # Optional: collection-wide permalink if a page has none set
    # permalink: /:title/

# Standard-Layouts
defaults:
  # All standalone pages under _pages use the simple page layout
  - scope:
      path: "_pages"
    values:
      layout: page
  # Posts use the page layout, which shows title and date
  - scope:
      type: posts
    values:
      layout: page

social:
  type: "Person"
  name: "Nicolin Dora"

markdown: kramdown
permalink: pretty