name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Build site
        run: bundle exec jekyll build --strict_front_matter
      - name: HTMLProofer checks
        run: |
          bundle exec htmlproofer ./_site \
            --check-external-hash \
            --check-opengraph \
            --empty-alt-ignore \
            --http-status-ignore 999 \
            --assume-extension \
            --disable-external true \
            --enforce-https true \
            --check-internal-hash true
